name: now deploy preview
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: amondnet/now-deployment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.NOW_ORG_ID }}
          now-project-id: ${{ secrets.STG_NOW_PROJECT_ID }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: blog-taku-dev
          SLACK_USERNAME: zeit
          SLACK_ICON: https://github.com/zeit?size=48
          SLACK_MESSAGE: 'https://stg-blog-taku-dev.now.sh/ :rocket:'
          SLACK_TITLE: Staging URL
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
